---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ansible-minio1
    image: centos:latest
    groups:
      - minio
    port_bindings: { 9001: 9000 }
    privileged: True
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
  - name: ansible-minio2
    image: centos:latest
    groups:
      - minio
    port_bindings: { 9002: 9000 }
    privileged: True
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
  - name: ansible-minio3
    image: centos:latest
    groups:
      - minio
    port_bindings: { 9003: 9000 }
    privileged: True
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
  - name: ansible-minio4
    image: centos:latest
    groups:
      - minio
    port_bindings: { 9004: 9000 }
    privileged: True
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: multi-node
verifier:
  name: testinfra
  lint:
    name: flake8
