---

- block:

    - name: "Download minio to {{ minio_server_bin_path }}"
      get_url:
        url: https://dl.minio.io/server/minio/release/linux-amd64/minio
        dest: "{{ minio_server_bin_path }}"
        mode: "0755"
        owner: "{{ minio_user }}"
        group: "{{ minio_group }}"

    - name: Create systemd service unit file for minio
      template:
        src: minio.service.j2
        dest: /etc/systemd/system/minio.service
        mode: "0644"
        owner: root
        group: root
      notify: Restart minio

    - name: Create directory for minio systemd unit configuration files
      file:
        state: directory
        path: /etc/systemd/system/minio.service.d

    - name: Create environment variables config for minio systemd unit file
      template:
        src: minio.conf.j2
        dest: /etc/systemd/system/minio.service.d/minio.conf
        mode: "0644"
        owner: root
        group: root
      notify: Restart minio

    - name: Start and enable minio
      systemd:
        name: minio
        state: started
        enabled: True
        daemon_reload: True

  tags:
    - minio
