---

- block:

    - name: Download minio to
      get_url:
        url: https://dl.minio.io/server/minio/release/linux-amd64/minio
        dest: "{{ minio_server_bin_path }}"
        mode: "0644"

    - name: Create systemd service unit file for minio
      template:
        src: minio.service.j2
        dest: /etc/systemd/system/minio.service
        # mode:
        owner: root
        group: root

    - name: Create default environment variables file for minio
      template:
        src: minio.j2
        dest: /etc/default/minio
        # mode:
        owner: root
        group: root

  tags:
    - minio
